/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelompok_6;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class frame_Beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_Beranda.class.getName());

    /**
     * Creates new form frame_Beranda
     */
    public frame_Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_Yakin = new javax.swing.JPanel();
        bAditya = new javax.swing.JButton();
        panel_Yakin1 = new javax.swing.JPanel();
        bAudi = new javax.swing.JButton();
        panel_Yakin2 = new javax.swing.JPanel();
        bKhabib = new javax.swing.JButton();
        panel_Yakin3 = new javax.swing.JPanel();
        bShofi = new javax.swing.JButton();
        panel_Yakin4 = new javax.swing.JPanel();
        bYakin = new javax.swing.JButton();
        panel_Yakin5 = new javax.swing.JPanel();
        bZaki = new javax.swing.JButton();
        panel_Content = new javax.swing.JPanel();
        panel_Atas = new javax.swing.JPanel();
        panel_Bio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Icon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_Bawah = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");

        panel_Sidebar.setBackground(java.awt.Color.blue);
        panel_Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));
        panel_Sidebar.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(java.awt.Color.blue);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Logo/Logo N.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kelompok 6 [PBO]");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        panel_Sidebar.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.blue);
        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        panel_Yakin.setLayout(new java.awt.BorderLayout());

        bAditya.setBackground(java.awt.Color.blue);
        bAditya.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAditya.setForeground(new java.awt.Color(255, 255, 255));
        bAditya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bAditya.setText("Biodata Aditya");
        bAditya.setIconTextGap(10);
        panel_Yakin.add(bAditya, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin);

        panel_Yakin1.setLayout(new java.awt.BorderLayout());

        bAudi.setBackground(java.awt.Color.blue);
        bAudi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAudi.setForeground(new java.awt.Color(255, 255, 255));
        bAudi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bAudi.setText("Biodata Audi");
        bAudi.setIconTextGap(10);
        panel_Yakin1.add(bAudi, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin1);

        panel_Yakin2.setLayout(new java.awt.BorderLayout());

        bKhabib.setBackground(java.awt.Color.blue);
        bKhabib.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKhabib.setForeground(new java.awt.Color(255, 255, 255));
        bKhabib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bKhabib.setText("Biodata Khabib");
        bKhabib.setIconTextGap(10);
        panel_Yakin2.add(bKhabib, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin2);

        panel_Yakin3.setLayout(new java.awt.BorderLayout());

        bShofi.setBackground(java.awt.Color.blue);
        bShofi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bShofi.setForeground(new java.awt.Color(255, 255, 255));
        bShofi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bShofi.setText("Biodata Shofi");
        bShofi.setIconTextGap(10);
        panel_Yakin3.add(bShofi, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin3);

        panel_Yakin4.setLayout(new java.awt.BorderLayout());

        bYakin.setBackground(java.awt.Color.blue);
        bYakin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bYakin.setForeground(new java.awt.Color(255, 255, 255));
        bYakin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bYakin.setText("Biodata Yakin");
        bYakin.setIconTextGap(10);
        panel_Yakin4.add(bYakin, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin4);

        panel_Yakin5.setLayout(new java.awt.BorderLayout());

        bZaki.setBackground(java.awt.Color.blue);
        bZaki.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bZaki.setForeground(new java.awt.Color(255, 255, 255));
        bZaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        bZaki.setText("Biodata Zaki");
        bZaki.setIconTextGap(10);
        panel_Yakin5.add(bZaki, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin5);

        panel_Sidebar.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_Sidebar, java.awt.BorderLayout.WEST);

        panel_Content.setLayout(new java.awt.BorderLayout());

        panel_Atas.setBackground(new java.awt.Color(255, 255, 255));
        panel_Atas.setLayout(new java.awt.BorderLayout());

        panel_Bio.setBackground(new java.awt.Color(255, 255, 255));
        panel_Bio.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        panel_Bio.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BIODATA MAHASISWA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        panel_Bio.add(jLabel1, java.awt.BorderLayout.LINE_START);

        panel_Atas.add(panel_Bio, java.awt.BorderLayout.LINE_START);

        panel_Icon.setBackground(new java.awt.Color(255, 255, 255));
        panel_Icon.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        panel_Icon.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-exit-35.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        panel_Icon.add(jLabel2, java.awt.BorderLayout.LINE_END);

        panel_Atas.add(panel_Icon, java.awt.BorderLayout.CENTER);

        panel_Content.add(panel_Atas, java.awt.BorderLayout.PAGE_START);

        panel_Bawah.setBackground(new java.awt.Color(255, 255, 255));
        panel_Bawah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panel_Bawah.setLayout(new java.awt.CardLayout());
        panel_Content.add(panel_Bawah, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_Content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_Beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAditya;
    private javax.swing.JButton bAudi;
    private javax.swing.JButton bKhabib;
    private javax.swing.JButton bShofi;
    private javax.swing.JButton bYakin;
    private javax.swing.JButton bZaki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_Atas;
    private javax.swing.JPanel panel_Bawah;
    private javax.swing.JPanel panel_Bio;
    private javax.swing.JPanel panel_Content;
    private javax.swing.JPanel panel_Icon;
    private javax.swing.JPanel panel_Sidebar;
    private javax.swing.JPanel panel_Yakin;
    private javax.swing.JPanel panel_Yakin1;
    private javax.swing.JPanel panel_Yakin2;
    private javax.swing.JPanel panel_Yakin3;
    private javax.swing.JPanel panel_Yakin4;
    private javax.swing.JPanel panel_Yakin5;
    // End of variables declaration//GEN-END:variables
}
